var belltimes = {
    "Monday": {
        "period": [
            "Start",
            "Period 1",
            "Period 2",
            "Assembly",
            "Recess",
            "Period 3",
            "Period 4",
            "Break",
            "Period 5",
            "Period 6",
            "Lunch 1st half",
            "Lunch 2nd half",
            "Period 7",
            "Period 8",
            "End"
        ],
        "times": [
            520,
            557,
            557,
            619,
            594,
            619,
            619,
            639,
            639,
            676,
            676,
            713,
            713,
            718,
            718,
            755,
            755,
            792,
            792,
            812,
            812,
            832,
            832,
            869,
            869,
            906
        ]
    },
    "Tuesday": {
        "period": [
            "Start",
            "Period 1",
            "Period 2",
            "Recess",
            "Period 3",
            "Period 4",
            "Break",
            "Period 5",
            "Period 6",
            "Lunch 1st half",
            "Lunch 2nd half",
            "Period 7",
            "Period 8",
            "End"
        ],
        "times": [
            520,
            561,
            561,
            601,
            601,
            621,
            621,
            661,
            661,
            701,
            701,
            706,
            706,
            746,
            746,
            786,
            786,
            806,
            806,
            826,
            826,
            866,
            866,
            906
        ]
    },
    "Wednesday": {
        "period": [
            "Start",
            "Period 1",
            "Period 2",
            "Recess",
            "Period 3",
            "Period 4",
            "Period 5",
            "Grade Sport",
            "End"
        ],
        "times": [
            515,
            520,
            520,
            558,
            558,
            596,
            596,
            611,
            611,
            649,
            649,
            687,
            687,
            750,
            750,
            870
        ]
    },
    "Thursday": {
        "period": [
            "Start",
            "Period 1",
            "Period 2",
            "Recess",
            "Period 3",
            "Period 4",
            "Break",
            "Period 5",
            "Period 6",
            "Lunch 1st half",
            "Lunch 2nd half",
            "Period 7",
            "Period 8",
            "End"
        ],
        "times": [
            520,
            561,
            561,
            601,
            601,
            621,
            621,
            661,
            661,
            701,
            701,
            706,
            706,
            746,
            746,
            786,
            786,
            806,
            806,
            826,
            826,
            866,
            866,
            906
        ]
    },
    "Friday": {
        "period": [
            "Start",
            "Period 1",
            "Period 2",
            "Recess",
            "Period 3",
            "Period 4",
            "Break",
            "Period 5",
            "Period 6",
            "Lunch 1st half",
            "Lunch 2nd half",
            "Period 7",
            "Period 8",
            "End"
        ],
        "times": [
            520,
            561,
            561,
            601,
            601,
            626,
            626,
            666,
            666,
            706,
            706,
            711,
            711,
            751,
            751,
            791,
            791,
            809,
            809,
            826,
            826,
            866,
            866,
            906
        ]
    }
};
